services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: blog_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5433"
    networks:
      - backend

networks:
  backend:
