
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: blogapi
  datasource:
    url: jdbc:postgresql://postgres:5432/blog_database
    username: postgres
    password: 123

    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
  main:
    lazy-initialization: true
    banner-mode: off
  security:
    user:
      name: admin
      password: 123
logging:
  level:
    web: debug
    root: info
    sql: debug
server:
  port: 8090
  servlet:
    session:
      timeout: 15m
info:
  app:
    name: blogapi
    version: 0
jwt:
  active-key-id: key1
  keys:
    - id: key1
      privateKey: z5kABUnsChEL4SFpssQXdlfHeb9ZV3Ih9k7DQal4x/Y=
      publicKey: +YSdNe4xox/HjqSKjomIqSafTkc9R6IZQtniIjvrOFA=
#    - id: key2
#      private: <base64>
#      public: <base64>
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  server:
    port: 8090
debug: true



