
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
#    drop-first: true
  #    contexts: dev # Optional: environment-based migrations
#    default-schema: public
  application:
    name: blogapi
  datasource:
#    url: jdbc:postgresql://postgres:5432/blog_database
    url: jdbc:postgresql://localhost:5432/blog_database
    username: postgres
    password: 123

    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: none
  main:
    lazy-initialization: true
    banner-mode: off
  security:
    user:
      name: admin
      password: 123
logging:
  level:
#    sun:
#      rmi:
#        transport:
#          tcp: INFO
#        loader: INFO
#    javax:
#      management:
#        remote:
#          rmi: INFO
#    org:
    web: debug
    root: info
    sql: debug
server:
  port: 8090
  servlet:
#    context-path:
    session:
      timeout: 15m
info:
  app:
    name: blogapi
    version: 0
jwt:
  active-key-id: key1
  keys:
    - id: key1
      privateKey: z5kABUnsChEL4SFpssQXdlfHeb9ZV3Ih9k7DQal4x/Y=
      publicKey: +YSdNe4xox/HjqSKjomIqSafTkc9R6IZQtniIjvrOFA=
#    - id: key2
#      private: <base64>
#      public: <base64>
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  server:
    port: 8090
debug: true



